# REF: https://www.postgresql.org/docs/current/libpq-pgpass.html
# Store the entire file in a secrets manager, not in version control
# This is used by Patroni
# <hostname>:<port>:<database>:<username>:<password>
0.0.0.0:5432:*:replicator:changeme
0.0.0.0:5432:*:rewind_user:changeme
0.0.0.0:5432:*:postgres:changeme

127.0.0.1:5432:*:replicator:changeme
127.0.0.1:5432:*:rewind_user:changeme
127.0.0.1:5432:*:postgres:changeme
