########################################################################
#  This config is a placeholder only for initially start pg server,    #
#  then later Patroni will completely take over (override) this config #
########################################################################

# <TYPE>  <DATABASE>  <USER>  <ADDRESS>  <METHOD>  [OPTIONS]
local   all             postgres                                peer
local   all             all                                     peer
host    all             all             0.0.0.0/0               md5
local   replication     all                                     peer
host    replication     all             0.0.0.0/0               md5
host    replication     all             127.0.0.1/32            md5
host    replication     all             10.0.0.0/8              md5
